### ISSUE TITLE
Push 'succeeds' even when it doesn't

### ISSUE THREAD

**Issue by petele** [GoogleChrome/push-encryption-node#23]
If I try to send a push message to a client who has unsubscribed, the promise is fulfilled and I have to look at the response returned. I expected the promise to be rejected and then catch the error there.

```
webpush.sendWebPush(message, subscription, gcmKey)
.then(function(resp) {
  // May have sent or may not have
})
.catch(function(resp) {
  // Expected this to be called if the message wan't sent
});
```

**Comment by gauntface** [comment]
Where are two options here:
1. We leave reject for unexpected errors (i.e. push server is down, network from your server is down) then use resolve for success, but we return an object with success <True or False> and the network response 
2. We reject for all problem cases and pass in the network response above and set some kind of error code in the catch that highlights it's a bad subscription.

I'm more pro option 1 than 2 simply because we have controlled cases and we have unexpected / bad error cases.

@petele what do you think?

**Comment by petele** [comment]
How do other similar APIs that return promises behave? 

While I don't love option 1, I can live with it if it's documented extremely well. The docs and samples should all include code snippets that check the success response for a true success.

**Comment by gauntface** [comment]
Spoke to Addy and he's pro option 2 like you so let's roll with that. It'll be demo code that is most important either way. Will look at a PR tomorrow for this hopefully.

**Comment by gauntface** [comment]
My current thinking for this would be this:

``` javascript
library.sendWebPush('Hello, World!', INVALID_SUBSCRIPTION)
.catch(err => {
  if (err.code === 'expired-subscription') {
      // TODO: Delete your subscription
      return;
  }
});
```

Does that seem good @addyosmani @petele ?

**Comment by petele** [comment]
Looks good to me! Thanks.

**Comment by addyosmani** [comment]
LGTM2

**Comment by gauntface** [comment]
It's in master - thanks all.
