### ISSUE TITLE
MessageTooBig

### ISSUE THREAD

**Issue by FallDi** [GoogleChrome/push-encryption-node#57]
Also i got such response from GCM

```
{ statusCode: 200,
  statusMessage: 'OK',
  body: '{"multicast_id":6777736059144782845,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MessageTooBig"}]}' }

```

For simple payload - "Hello". Encoded payload is too big, any way to resolve it? I understand that encrypted payload is big, but how to pass normal data in this case? But sometimes for same payload it works...

**Comment by samthor** [comment]
The [relevant](https://tools.ietf.org/html/draft-ietf-webpush-protocol-07#section-7.2) [specifications](https://tools.ietf.org/html/draft-ietf-webpush-encryption-03#section-3.2) (and [GCM for older Google clients](https://en.wikipedia.org/wiki/Google_Cloud_Messaging#Technical_details)) all specify that the maximum size is 4096 bytes (and that in practice it should be slightly lower due to encoding).

Are you sure your payload is <4kb after encryption?

**Comment by FallDi** [comment]
It problem can be closed. 
We use base64 url encode for raw_data. It was wrong. Classic base64 help resolve it issue. Thanks.

```
body = JSON.stringify({
      "registration_ids": ["cIKD0Ykm2ZI:APA91bG-OP...."],
      "raw_data": payload.ciphertext.toString('base64')
    });
```
